FROM node:18.17.0-slim
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl
COPY package.json .dockerignore .
RUN yarn install
COPY . .
COPY ./environment/.env.production ./.env
RUN ./node_modules/.bin/prisma generate
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
