name: remote ssh command
on:
  push:
    branches: ["master"]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SHH_PRIVATE_KEY }}
        port: 22
        script: node -v